# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Research
    url: /researches/
    identifier: research
    weight: 11
  - name: Wireless Communication Systems and Dedicated Baseband Processors
    url: /researches/Wireless-Communication-Systems-and-Dedicated-Baseband-Processors/
    parent: research
    weight: 1
  - name: AI Chips and Neural Network Processors
    url: /researches/AI-Chips-and-Neural-Network-Processors/
    parent: research
    weight: 2
  - name: Communication–AI Fusion and Integrated Compute–Communication Architectures for 6G
    url: /researches/Communication–AI-Fusion-and-Integrated-Compute–Communication-Architectures-for-6G/
    parent: research
    weight: 3
  - name: Project
    url: /projects/
    weight: 12
  - name: Teaching
    url: /teaching/
    weight: 13
  - name: People
    url: /people/
    weight: 14
  - name: Publications
    url: /publications/
    weight: 15
  - name: Events
    url: /events
    weight: 16
  - name: Join Us
    url: /opportunities/
    weight: 17
